### ISSUE TITLE
Digital inputs

### ISSUE THREAD

**Issue by jcul3351** [strykeforce/thirdcoast#6]
We need the ability to read the digital inputs.  TCT could just read all 10 ports and report them all at once.  The grapher could show all 10 ports so that you could watch which ever combination you wanted.

**Comment by jhh** [comment]
I think the way this should work is that if you go in and scan the 10 digital inputs via the `tct` command-line then all 10 are added to the grapher inventory. If you never select that menu option, then they don't show up in the grapher. That way we avoid cluttering up the inventory for the majority use-case where we're not looking at inputs.

@jcul3351 - your call since you'll be using `tct` more than me.

Also, where do you want it on the DIO sub-menu?

**Comment by jcul3351** [comment]
I would agree.  The basic rule is :  you must look at something at least once with TCT for it to show up in the inventory on the grapher.  If the grapher gets too populated, just restart it to clean things up.
